import { Inter } from 'next/font/google';
import { Container } from '@/shared/ui/container';
import type { Metadata } from 'next';
import '@/app/styles/globals.css';

export const metadata: Metadata = {
  title: 'SkillSwap | Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  variable: '--font-inter',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-mode='light' className={inter.className}>
      <body>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
