import type { Metadata } from 'next';
import './styles/globals.css';
import { Container } from '@/shared/ui/container';

export const metadata: Metadata = {
  title: 'SkillSwap | Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
