#!/usr/bin/env bash

message="$(cat $1)"
requiredPattern="^(add|cut|fix|refactor|optimise|merge|chore|infra|feat): .*$"

if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "-"
  echo "Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<type>: <what was done>"
  echo "Allowed types: add, cut, fix, bump, make, start, stop, refactor, reformat, optimise, document, merge, chore, infra"
  echo "Example: fix login button"
  echo "Example with type prefix: chore: update dependencies"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi